# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

self-hosted-runner:
  labels:
    - linux-amd64-cpu4
    - linux-amd64-cpu8
    - linux-arm64-cpu8
    - linux-amd64-gpu-t4-latest-1
    - linux-amd64-gpu-h100-latest-1
    - linux-amd64-gpu-rtxpro6000-latest-1
